language: node_js
node_js:
- 14
env:
  global:
    secure: eKi/nXlGtG7kUd4SS6zmuyjwYPRCKZYNKtF+eDCcGZz0/MuAQta2lTMPJ/k6Lx8SvMDyzJr0YmG3D5k1X11w0ZMCWnFCUiLJopb2j0RVrWEPUI+b+/M2Sl5n9zQXpE7AUJtEDrJSncfHcHsgnPILrNzx5Nz38+yPgMHzjoKwDUQOptJo4iOPwCjke3qdicm7XtXnitY4ca1WDVHsBBLxUZJbPSc6ZTHY3NwNQaS4usPDwcUax68AhkSciH9ZGxp11EyEjjXkQrDs7/R+pQmV+QvzdtKszzUnphnrvW9Mgie8dO0lRTTXIcCJBmFQngK2dWzO+j2BS0ro89rM7cctClKRg2EftYqO1aHTugoeDuBsZSPeoZ3BLlU2w1dyraF32XoFyGIAb3jLpP+emjhK/i/7MKnFpWTDiGiDiBmy64uCJGkdNJc2BcBrD+WO+uukmUGH8b0ZSHtyRd2bXlWlhiLwfEfgOor0rvgrYi14nHODWwCSdiGC+91p47gSjjT5JLnTD99IUHSvwUgKBr14D0h0nzAa9OvA/6JnlpQN0//dYfL9WumiD3gz9sWtEPeRZzCDfqwa4lO1MDiYKsYGA+kqbwnrvplEWK7ei0qccqzfbc37/iHy8sQv5Fs9a/1TKfaC460lRmsqe8eu37MNg7g4+FAtk2sduLqPwhge0ak=
